server:
  port: 8888

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false

queue:
  notification: NOTIFICATION
  notification-dlq: NOTIFICATION_DLQ
