server:
  port: 8383

spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    url: jdbc:postgresql://${DB_NAME:localhost}:5432/ms-customer
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
